Script started on 2019-07-06 14:42:02+02:00 [TERM="xterm-kitty" TTY="/dev/pts/0" COLUMNS="75" LINES="47"]
[?25l[1m[7m#[27m[1m[0m                                                                           [0m[27m[24m[J[1m[0m[1m[31mroot[0m[31m[39m[1m [0m[1min [0m[1m[33mlittle-penguin/04[0m[33m[39m[1m [0m[K[4 q[?25l[?2004h[1m[31md[0m[39m[1m[31md[1m[31mm[0m[39m[1m[31md[1m[31mm[1m[31me[0m[39m[1m[31me[1m[31mw[0m[39m[1m[31mw[1m[31ms[0m[39m[1m[31mw[0m[39m[0m[39m [1m[31me[0m[39m[0m[39m [1m[31me[1m[31ms[0m[39m[0m[32md[0m[32mm[0m[32me[0m[32ms[32mg[39m [36m-[39m[36m-[36mw[39m[4 q[?25l[?2004l
[32m[    0.000000] [0mLinux version 5.2.0-rc4 (root@dengstra) (gcc version 8.2.0 (GCC)) #1 SMP Sun Jun 9 16:00:14 CEST 2019
[32m[    0.000000] [0m[33mCommand line[0m: BOOT_IMAGE=/vmlinuz-5.2.0-rc4 linux-5.2.0-rc4 root=/dev/sda5 ro
[32m[    0.000000] [0m[33mx86/fpu[0m: Supporting XSAVE feature 0x001: 'x87 floating point registers'
[32m[    0.000000] [0m[33mx86/fpu[0m: Supporting XSAVE feature 0x002: 'SSE registers'
[32m[    0.000000] [0m[33mx86/fpu[0m: Supporting XSAVE feature 0x004: 'AVX registers'
[32m[    0.000000] [0m[33mx86/fpu[0m: xstate_offset[2]:  576, xstate_sizes[2]:  256
[32m[    0.000000] [0m[33mx86/fpu[0m: Enabled xstate features 0x7, context size is 832 bytes, using 'standard' format.
[32m[    0.000000] [0mBIOS-provided physical RAM map:
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x0000000000000000-0x000000000009fbff] usable
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x000000000009fc00-0x000000000009ffff] reserved
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x00000000000f0000-0x00000000000fffff] reserved
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x0000000000100000-0x000000003ffdffff] usable
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x000000003ffe0000-0x000000003fffffff] reserved
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x00000000feffc000-0x00000000feffffff] reserved
[32m[    0.000000] [0m[33mBIOS-e820[0m: [mem 0x00000000fffc0000-0x00000000ffffffff] reserved
[32m[    0.000000] [0m[33mNX (Execute Disable) protection[0m: active
[32m[    0.000000] [0mSMBIOS 2.8 present.
[32m[    0.000000] [0m[33mDMI[0m: QEMU Standard PC (i440FX + PIIX, 1996), BIOS 1.12.0-20181126_142135-anatol 04/01/2014
[32m[    0.000000] [0m[33mtsc[0m: Fast TSC calibration using PIT
[32m[    0.000000] [0m[33mtsc[0m: Detected 2600.268 MHz processor
[32m[    0.001357] [0m[33me820[0m: update [mem 0x00000000-0x00000fff] usable ==> reserved
[32m[    0.001359] [0m[33me820[0m: remove [mem 0x000a0000-0x000fffff] usable
[32m[    0.001362] [0mlast_pfn = 0x3ffe0 max_arch_pfn = 0x400000000
[32m[    0.001382] [0m[33mMTRR default type[0m: write-back
[32m[    0.001383] [0mMTRR fixed ranges enabled:
[32m[    0.001383] [0m  00000-9FFFF write-back
[32m[    0.001384] [0m  A0000-BFFFF uncachable
[32m[    0.001384] [0m  C0000-FFFFF write-protect
[32m[    0.001385] [0mMTRR variable ranges enabled:
[32m[    0.001386] [0m  0 base 0080000000 mask FF80000000 uncachable
[32m[    0.001386] [0m  1 disabled
[32m[    0.001386] [0m  2 disabled
[32m[    0.001387] [0m  3 disabled
[32m[    0.001387] [0m  4 disabled
[32m[    0.001387] [0m  5 disabled
[32m[    0.001387] [0m  6 disabled
[32m[    0.001388] [0m  7 disabled
[32m[    0.001395] [0m[33mx86/PAT[0m: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT  
[32m[    0.004953] [0mfound SMP MP-table at [mem 0x000f5cb0-0x000f5cbf]
[32m[    0.005054] [0m[33mcheck[0m: Scanning 1 areas for low memory corruption
[32m[    0.005125] [0mUsing GB pages for direct mapping
[32m[    0.005129] [0mBRK [0x07001000, 0x07001fff] PGTABLE
[32m[    0.005132] [0mBRK [0x07002000, 0x07002fff] PGTABLE
[32m[    0.005134] [0mBRK [0x07003000, 0x07003fff] PGTABLE
[32m[    0.005157] [0mBRK [0x07004000, 0x07004fff] PGTABLE
[32m[    0.005189] [0mBRK [0x07005000, 0x07005fff] PGTABLE
[32m[    0.005219] [0m[33mACPI[0m: Early table checksum verification disabled
[32m[    0.005308] [0m[33mACPI[0m: RSDP 0x00000000000F5AE0 000014 (v00 BOCHS )
[32m[    0.005320] [0m[33mACPI[0m: RSDT 0x000000003FFE156F 000030 (v01 BOCHS  BXPCRSDT 00000001 BXPC 00000001)
[32m[    0.005326] [0m[33mACPI[0m: FACP 0x000000003FFE144B 000074 (v01 BOCHS  BXPCFACP 00000001 BXPC 00000001)
[32m[    0.005331] [0m[33mACPI[0m: DSDT 0x000000003FFE0040 00140B (v01 BOCHS  BXPCDSDT 00000001 BXPC 00000001)
[32m[    0.005334] [0m[33mACPI[0m: FACS 0x000000003FFE0000 000040
[32m[    0.005336] [0m[33mACPI[0m: APIC 0x000000003FFE14BF 000078 (v01 BOCHS  BXPCAPIC 00000001 BXPC 00000001)
[32m[    0.005338] [0m[33mACPI[0m: HPET 0x000000003FFE1537 000038 (v01 BOCHS  BXPCHPET 00000001 BXPC 00000001)
[32m[    0.005346] [0m[33mACPI[0m: Local APIC address 0xfee00000
[32m[    0.005670] [0mNo NUMA configuration found
[32m[    0.005672] [0mFaking a node at [mem 0x0000000000000000-0x000000003ffdffff]
[32m[    0.005677] [0mNODE_DATA(0) allocated [mem 0x3ffdc000-0x3ffdffff]
[32m[    0.008724] [0mZone ranges:
[32m[    0.008738] [0m  DMA      [mem 0x0000000000001000-0x0000000000ffffff]
[32m[    0.008740] [0m  DMA32    [mem 0x0000000001000000-0x000000003ffdffff]
[32m[    0.008742] [0m  Normal   empty
[32m[    0.008743] [0mMovable zone start for each node
[32m[    0.008744] [0mEarly memory node ranges
[32m[    0.008745] [0m[33m  node   0[0m: [mem 0x0000000000001000-0x000000000009efff]
[32m[    0.008747] [0m[33m  node   0[0m: [mem 0x0000000000100000-0x000000003ffdffff]
[32m[    0.009997] [0m[33mZeroed struct page in unavailable ranges[0m: 98 pages
[32m[    0.009999] [0mInitmem setup node 0 [mem 0x0000000000001000-0x000000003ffdffff]
[32m[    0.010001] [0m[33mOn node 0 totalpages[0m: 262014
[32m[    0.010002] [0m[33m  DMA zone[0m: 64 pages used for memmap
[32m[    0.010002] [0m[33m  DMA zone[0m: 21 pages reserved
[32m[    0.010003] [0m[33m  DMA zone[0m: 3998 pages, LIFO batch:0
[32m[    0.010040] [0m[33m  DMA32 zone[0m: 4032 pages used for memmap
[32m[    0.010041] [0m[33m  DMA32 zone[0m: 258016 pages, LIFO batch:63
[32m[    0.016429] [0m[33mACPI[0m: PM-Timer IO Port: 0x608
[32m[    0.016432] [0m[33mACPI[0m: Local APIC address 0xfee00000
[32m[    0.016437] [0m[33mACPI[0m: LAPIC_NMI (acpi_id[0xff] dfl dfl lint[0x1])
[32m[    0.016476] [0m[33mIOAPIC[0][0m: apic_id 0, version 17, address 0xfec00000, GSI 0-23
[32m[    0.016478] [0m[33mACPI[0m: INT_SRC_OVR (bus 0 bus_irq 0 global_irq 2 dfl dfl)
[32m[    0.016479] [0m[33mACPI[0m: INT_SRC_OVR (bus 0 bus_irq 5 global_irq 5 high level)
[32m[    0.016480] [0m[33mACPI[0m: INT_SRC_OVR (bus 0 bus_irq 9 global_irq 9 high level)
[32m[    0.016481] [0m[33mACPI[0m: INT_SRC_OVR (bus 0 bus_irq 10 global_irq 10 high level)
[32m[    0.016482] [0m[33mACPI[0m: INT_SRC_OVR (bus 0 bus_irq 11 global_irq 11 high level)
[32m[    0.016483] [0m[33mACPI[0m: IRQ0 used by override.
[32m[    0.016483] [0m[33mACPI[0m: IRQ5 used by override.
[32m[    0.016484] [0m[33mACPI[0m: IRQ9 used by override.
[32m[    0.016484] [0m[33mACPI[0m: IRQ10 used by override.
[32m[    0.016484] [0m[33mACPI[0m: IRQ11 used by override.
[32m[    0.016486] [0mUsing ACPI (MADT) for SMP configuration information
[32m[    0.016487] [0m[33mACPI[0m: HPET id: 0x8086a201 base: 0xfed00000
[32m[    0.016493] [0m[33msmpboot[0m: Allowing 1 CPUs, 0 hotplug CPUs
[32m[    0.016500] [0m[33mPM[0m: Registered nosave memory: [mem 0x00000000-0x00000fff]
[32m[    0.016501] [0m[33mPM[0m: Registered nosave memory: [mem 0x0009f000-0x0009ffff]
[32m[    0.016502] [0m[33mPM[0m: Registered nosave memory: [mem 0x000a0000-0x000effff]
[32m[    0.016503] [0m[33mPM[0m: Registered nosave memory: [mem 0x000f0000-0x000fffff]
[32m[    0.016504] [0m[mem 0x40000000-0xfeffbfff] available for PCI devices
[32m[    0.016507] [0m[33mclocksource[0m: refined-jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1910969940391419 ns
[32m[    0.016510] [0m[33msetup_percpu[0m: NR_CPUS:64 nr_cpumask_bits:64 nr_cpu_ids:1 nr_node_ids:1
[32m[    0.017422] [0m[33mpercpu[0m: Embedded 51 pages/cpu s170968 r8192 d29736 u2097152
[32m[    0.017429] [0m[33mpcpu-alloc[0m: s170968 r8192 d29736 u2097152 alloc=1*2097152
[32m[    0.017429] [0m[33mpcpu-alloc[0m: [0] 0 
[32m[    0.017442] [0m[33mBuilt 1 zonelists, mobility grouping on.  Total pages[0m: 257897
[32m[    0.017443] [0m[33mPolicy zone[0m: DMA32
[32m[    0.017445] [0m[33mKernel command line[0m: BOOT_IMAGE=/vmlinuz-5.2.0-rc4 linux-5.2.0-rc4 root=/dev/sda5 ro
[32m[    0.017513] [0m[33mCalgary[0m: detecting Calgary via BIOS EBDA area
[32m[    0.017514] [0m[33mCalgary[0m: Unable to locate Rio Grande table in EBDA - bailing!
[32m[    0.019877] [0m[33mMemory[0m: 1006524K/1048056K available (14340K kernel code, 1315K rwdata, 3116K rodata, 1320K init, 1320K bss, 41532K reserved, 0K cma-reserved)
[32m[    0.021034] [0m[33mSLUB[0m: HWalign=64, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[32m[    0.021041] [0m[33mKernel/User page tables isolation[0m: enabled
[32m[    0.022335] [0m[33mrcu[0m: Hierarchical RCU implementation.
[32m[    0.022337] [0m[33mrcu[0m: 	RCU event tracing is enabled.
[32m[    0.022338] [0m[33mrcu[0m: 	RCU restricting CPUs from NR_CPUS=64 to nr_cpu_ids=1.
[32m[    0.022339] [0m[33mrcu[0m: RCU calculated value of scheduler-enlistment delay is 100 jiffies.
[32m[    0.022340] [0m[33mrcu[0m: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=1
[32m[    0.022473] [0m[33mNR_IRQS[0m: 4352, nr_irqs: 256, preallocated irqs: 16
[32m[    0.022702] [0m[33mrandom[0m: get_random_bytes called from start_kernel+0x2c8/0x49b with crng_init=0
[32m[    0.033287] [0m[33mConsole[0m: colour VGA+ 80x25
[32m[    0.072787] [0m[33mprintk[0m: console [tty0] enabled
[32m[    0.073193] [0m[33mACPI[0m: Core revision 20190509
[32m[    0.073779] [0m[33mclocksource[0m: hpet: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604467 ns
[32m[    0.074566] [0mhpet clockevent registered
[32m[    0.074589] [0m[33mAPIC[0m: Switch to symmetric I/O mode setup
[32m[    0.076173] [0m[33m..TIMER[0m: vector=0x30 apic1=0 pin1=2 apic2=-1 pin2=-1
[32m[    0.081599] [0m[33mclocksource[0m: tsc-early: mask: 0xffffffffffffffff max_cycles: 0x257b394a470, max_idle_ns: 440795215957 ns
[32m[    0.082341] [0mCalibrating delay loop (skipped), value calculated using timer frequency.. 5200.53 BogoMIPS (lpj=2600268)
[32m[    0.083340] [0m[33mpid_max[0m: default: 32768 minimum: 301
[32m[    0.083762] [0m[33mLSM[0m: Security Framework initializing
[32m[    0.084344] [0m[33mSELinux[0m:  Initializing.
[32m[    0.084740] [0m*** VALIDATE SELinux ***
[32m[    0.085471] [0m[33mDentry cache hash table entries[0m: 131072 (order: 8, 1048576 bytes)
[32m[    0.086359] [0m[33mInode-cache hash table entries[0m: 65536 (order: 7, 524288 bytes)
[32m[    0.087354] [0m[33mMount-cache hash table entries[0m: 2048 (order: 2, 16384 bytes)
[32m[    0.087853] [0m[33mMountpoint-cache hash table entries[0m: 2048 (order: 2, 16384 bytes)
[32m[    0.088429] [0m*** VALIDATE proc ***
[32m[    0.088827] [0m*** VALIDATE cgroup1 ***
[32m[    0.089341] [0m*** VALIDATE cgroup2 ***
[32m[    0.089789] [0m[33mx86/cpu[0m: User Mode Instruction Prevention (UMIP) activated
[32m[    0.090377] [0m[33mLast level iTLB entries[0m: 4KB 0, 2MB 0, 4MB 0
[32m[    0.090806] [0m[33mLast level dTLB entries[0m: 4KB 0, 2MB 0, 4MB 0, 1GB 0
[32m[    0.091342] [0m[33mSpectre V2 [0m: Mitigation: Full generic retpoline
[32m[    0.091778] [0m[33mSpectre V2 [0m: Spectre v2 / SpectreRSB mitigation: Filling RSB on context switch
[32m[    0.092341] [0m[33mSpectre V2 [0m: Enabling Restricted Speculation for firmware calls
[32m[    0.092820] [0m[33mSpectre V2 [0m: mitigation: Enabling conditional Indirect Branch Prediction Barrier
[32m[    0.093341] [0m[33mSpeculative Store Bypass[0m: Mitigation: Speculative Store Bypass disabled via prctl and seccomp
[32m[    0.094346] [0m[33mMDS[0m: Vulnerable: Clear CPU buffers attempted, no microcode
[32m[    0.100743] [0m[33mFreeing SMP alternatives memory[0m: 40K
[32m[    0.101457] [0mTSC deadline timer enabled
[32m[    0.101474] [0m[33msmpboot[0m: CPU0: Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz (family: 0x6, model: 0x45, stepping: 0x1)
[32m[    0.102511] [0m[33mPerformance Events[0m: Haswell events, Intel PMU driver.
[32m[    0.103361] [0m[33m... version[0m:                2
[32m[    0.104162] [0m[33m... bit width[0m:              48
[32m[    0.104344] [0m[33m... generic registers[0m:      4
[32m[    0.105289] [0m[33m... value mask[0m:             0000ffffffffffff
[32m[    0.105349] [0m[33m... max period[0m:             000000007fffffff
[32m[    0.106074] [0m[33m... fixed-purpose events[0m:   3
[32m[    0.106341] [0m[33m... event mask[0m:             000000070000000f
[32m[    0.107096] [0m[33mrcu[0m: Hierarchical SRCU implementation.
[32m[    0.107396] [0m[33msmp[0m: Bringing up secondary CPUs ...
[32m[    0.108169] [0m[33msmp[0m: Brought up 1 node, 1 CPU
[32m[    0.108342] [0m[33msmpboot[0m: Max logical packages: 1
[32m[    0.109023] [0m[33msmpboot[0m: Total of 1 processors activated (5200.53 BogoMIPS)
[32m[    0.109453] [0m[33mdevtmpfs[0m: initialized
[32m[    0.110262] [0m[33mclocksource[0m: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
[32m[    0.110345] [0m[33mfutex hash table entries[0m: 256 (order: 2, 16384 bytes)
[32m[    0.111141] [0m[33mPM[0m: RTC time: 12:11:15, date: 2019-07-06
[32m[    0.111395] [0m[33mNET[0m: Registered protocol family 16
[32m[    0.112188] [0m[33maudit[0m: initializing netlink subsys (disabled)
[32m[    0.112438] [0m[33mcpuidle[0m: using governor menu
[32m[    0.113305] [0m[33mACPI[0m: bus type PCI registered
[32m[    0.113409] [0m[33mPCI[0m: Using configuration type 1 for base access
[32m[    0.114238] [0m[33mcore[0m: PMU erratum BJ122, BV98, HSD29 workaround disabled, HT off
[32m[    0.115361] [0m[33maudit[0m: type=2000 audit(1562415074.037:1): state=initialized audit_enabled=0 res=1
[32m[    0.117025] [0mHugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[32m[    0.117569] [0m[33mcryptomgr_test (20) used greatest stack depth[0m: 15448 bytes left
[32m[    0.118409] [0m[33mkworker/u2:0 (22) used greatest stack depth[0m: 14536 bytes left
[32m[    0.119329] [0m[33mkworker/u2:0 (26) used greatest stack depth[0m: 14088 bytes left
[32m[    0.119804] [0m[33mACPI[0m: Added _OSI(Module Device)
[32m[    0.120347] [0m[33mACPI[0m: Added _OSI(Processor Device)
[32m[    0.121122] [0m[33mACPI[0m: Added _OSI(3.0 _SCP Extensions)
[32m[    0.121342] [0m[33mACPI[0m: Added _OSI(Processor Aggregator Device)
[32m[    0.122071] [0m[33mACPI[0m: Added _OSI(Linux-Dell-Video)
[32m[    0.122346] [0m[33mACPI[0m: Added _OSI(Linux-Lenovo-NV-HDMI-Audio)
[32m[    0.123097] [0m[33mACPI[0m: Added _OSI(Linux-HPI-Hybrid-Graphics)
[32m[    0.123982] [0m[33mACPI[0m: 1 ACPI AML tables successfully acquired and loaded
[32m[    0.125553] [0m[33mACPI[0m: Interpreter enabled
[32m[    0.126331] [0m[33mACPI[0m: (supports S0 S3 S4 S5)
[32m[    0.126346] [0m[33mACPI[0m: Using IOAPIC for interrupt routing
[32m[    0.127097] [0m[33mPCI[0m: Using host bridge windows from ACPI; if necessary, use "pci=nocrs" and report a bug
[32m[    0.127420] [0m[33mACPI[0m: Enabled 2 GPEs in block 00 to 0F
[32m[    0.129650] [0m[33mACPI[0m: PCI Root Bridge [PCI0] (domain 0000 [bus 00-ff])
[32m[    0.130351] [0m[33macpi PNP0A03:00[0m: _OSC: OS supports [ASPM ClockPM Segments MSI HPX-Type3]
[32m[    0.131348] [0m[33macpi PNP0A03:00[0m[1m: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.[0m
[32m[    0.132369] [0mPCI host bridge to bus 0000:00
[32m[    0.133052] [0m[33mpci_bus 0000:00[0m: root bus resource [io  0x0000-0x0cf7 window]
[32m[    0.133342] [0m[33mpci_bus 0000:00[0m: root bus resource [io  0x0d00-0xffff window]
[32m[    0.134092] [0m[33mpci_bus 0000:00[0m: root bus resource [mem 0x000a0000-0x000bffff window]
[32m[    0.134343] [0m[33mpci_bus 0000:00[0m: root bus resource [mem 0x40000000-0xfebfffff window]
[32m[    0.135364] [0m[33mpci_bus 0000:00[0m: root bus resource [mem 0x100000000-0x17fffffff window]
[32m[    0.136350] [0m[33mpci_bus 0000:00[0m: root bus resource [bus 00-ff]
[32m[    0.137385] [0m[33mpci 0000:00:00.0[0m: [8086:1237] type 00 class 0x060000
[32m[    0.138783] [0m[33mpci 0000:00:01.0[0m: [8086:7000] type 00 class 0x060100
[32m[    0.139880] [0m[33mpci 0000:00:01.1[0m: [8086:7010] type 00 class 0x010180
[32m[    0.142360] [0m[33mpci 0000:00:01.1[0m: reg 0x20: [io  0xc060-0xc06f]
[32m[    0.144164] [0m[33mpci 0000:00:01.1[0m: legacy IDE quirk: reg 0x10: [io  0x01f0-0x01f7]
[32m[    0.144344] [0m[33mpci 0000:00:01.1[0m: legacy IDE quirk: reg 0x14: [io  0x03f6]
[32m[    0.145321] [0m[33mpci 0000:00:01.1[0m: legacy IDE quirk: reg 0x18: [io  0x0170-0x0177]
[32m[    0.145343] [0m[33mpci 0000:00:01.1[0m: legacy IDE quirk: reg 0x1c: [io  0x0376]
[32m[    0.146233] [0m[33mpci 0000:00:01.2[0m: [8086:7020] type 00 class 0x0c0300
[32m[    0.147636] [0m[33mpci 0000:00:01.2[0m: reg 0x20: [io  0xc040-0xc05f]
[32m[    0.149506] [0m[33mpci 0000:00:01.3[0m: [8086:7113] type 00 class 0x068000
[32m[    0.150673] [0m[33mpci 0000:00:01.3[0m: quirk: [io  0x0600-0x063f] claimed by PIIX4 ACPI
[32m[    0.151355] [0m[33mpci 0000:00:01.3[0m: quirk: [io  0x0700-0x070f] claimed by PIIX4 SMB
[32m[    0.152508] [0m[33mpci 0000:00:02.0[0m: [1234:1111] type 00 class 0x030000
[32m[    0.154356] [0m[33mpci 0000:00:02.0[0m: reg 0x10: [mem 0xfd000000-0xfdffffff pref]
[32m[    0.160367] [0m[33mpci 0000:00:02.0[0m: reg 0x18: [mem 0xfebf0000-0xfebf0fff]
[32m[    0.167861] [0m[33mpci 0000:00:02.0[0m: reg 0x30: [mem 0xfebe0000-0xfebeffff pref]
[32m[    0.168520] [0m[33mpci 0000:00:03.0[0m: [8086:100e] type 00 class 0x020000
[32m[    0.170349] [0m[33mpci 0000:00:03.0[0m: reg 0x10: [mem 0xfebc0000-0xfebdffff]
[32m[    0.172347] [0m[33mpci 0000:00:03.0[0m: reg 0x14: [io  0xc000-0xc03f]
[32m[    0.178379] [0m[33mpci 0000:00:03.0[0m: reg 0x30: [mem 0xfeb80000-0xfebbffff pref]
[32m[    0.180619] [0m[33mACPI[0m: PCI Interrupt Link [LNKA] (IRQs 5 *10 11)
[32m[    0.181453] [0m[33mACPI[0m: PCI Interrupt Link [LNKB] (IRQs 5 *10 11)
[32m[    0.182436] [0m[33mACPI[0m: PCI Interrupt Link [LNKC] (IRQs 5 10 *11)
[32m[    0.183434] [0m[33mACPI[0m: PCI Interrupt Link [LNKD] (IRQs 5 10 *11)
[32m[    0.184400] [0m[33mACPI[0m: PCI Interrupt Link [LNKS] (IRQs *9)
[32m[    0.185538] [0m[33mpci 0000:00:02.0[0m: vgaarb: setting as boot VGA device
[32m[    0.186339] [0m[33mpci 0000:00:02.0[0m: vgaarb: VGA device added: decodes=io+mem,owns=io+mem,locks=none
[32m[    0.186343] [0m[33mpci 0000:00:02.0[0m: vgaarb: bridge control possible
[32m[    0.187092] [0m[33mvgaarb[0m: loaded
[32m[    0.187385] [0mSCSI subsystem initialized
[32m[    0.188132] [0mlibata version 3.00 loaded.
[32m[    0.188147] [0m[33mACPI[0m: bus type USB registered
[32m[    0.188378] [0m[33musbcore[0m: registered new interface driver usbfs
[32m[    0.189166] [0m[33musbcore[0m: registered new interface driver hub
[32m[    0.189360] [0m[33musbcore[0m: registered new device driver usb
[32m[    0.190376] [0m[33mpps_core[0m: LinuxPPS API ver. 1 registered
[32m[    0.191158] [0m[33mpps_core[0m: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[32m[    0.191350] [0mPTP clock support registered
[32m[    0.192084] [0m[33mEDAC MC[0m: Ver: 3.0.0
[32m[    0.192474] [0mAdvanced Linux Sound Architecture Driver Initialized.
[32m[    0.193230] [0m[33mPCI[0m: Using ACPI for IRQ routing
[32m[    0.193342] [0m[33mPCI[0m: pci_cache_line_size set to 64 bytes
[32m[    0.193412] [0m[33me820[0m: reserve RAM buffer [mem 0x0009fc00-0x0009ffff]
[32m[    0.193413] [0m[33me820[0m: reserve RAM buffer [mem 0x3ffe0000-0x3fffffff]
[32m[    0.193486] [0m[33mNetLabel[0m: Initializing
[32m[    0.194167] [0m[33mNetLabel[0m:  domain hash size = 128
[32m[    0.194341] [0m[33mNetLabel[0m:  protocols = UNLABELED CIPSOv4 CALIPSO
[32m[    0.195105] [0m[33mNetLabel[0m:  unlabeled traffic allowed by default
[32m[    0.195423] [0m[33mhpet0[0m: at MMIO 0xfed00000, IRQs 2, 8, 0
[32m[    0.196139] [0m[33mhpet0[0m: 3 comparators, 64-bit 100.000000 MHz counter
[32m[    0.199379] [0m[33mclocksource[0m: Switched to clocksource tsc-early
[32m[    0.259970] [0m[33mVFS[0m: Disk quotas dquot_6.6.0
[32m[    0.260698] [0m[33mVFS[0m: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[32m[    0.261486] [0m*** VALIDATE hugetlbfs ***
[32m[    0.262227] [0m[33mpnp[0m: PnP ACPI init
[32m[    0.262936] [0m[33mpnp 00:00[0m: Plug and Play ACPI device, IDs PNP0b00 (active)
[32m[    0.262959] [0m[33mpnp 00:01[0m: Plug and Play ACPI device, IDs PNP0303 (active)
[32m[    0.262973] [0m[33mpnp 00:02[0m: Plug and Play ACPI device, IDs PNP0f13 (active)
[32m[    0.262980] [0m[33mpnp 00:03[0m: [dma 2]
[32m[    0.262987] [0m[33mpnp 00:03[0m: Plug and Play ACPI device, IDs PNP0700 (active)
[32m[    0.263025] [0m[33mpnp 00:04[0m: Plug and Play ACPI device, IDs PNP0400 (active)
[32m[    0.263053] [0m[33mpnp 00:05[0m: Plug and Play ACPI device, IDs PNP0501 (active)
[32m[    0.263186] [0m[33mpnp[0m: PnP ACPI: found 6 devices
[32m[    0.269116] [0m[33mclocksource[0m: acpi_pm: mask: 0xffffff max_cycles: 0xffffff, max_idle_ns: 2085701024 ns
[32m[    0.270398] [0m[33mpci_bus 0000:00[0m: resource 4 [io  0x0000-0x0cf7 window]
[32m[    0.271144] [0m[33mpci_bus 0000:00[0m: resource 5 [io  0x0d00-0xffff window]
[32m[    0.271906] [0m[33mpci_bus 0000:00[0m: resource 6 [mem 0x000a0000-0x000bffff window]
[32m[    0.272678] [0m[33mpci_bus 0000:00[0m: resource 7 [mem 0x40000000-0xfebfffff window]
[32m[    0.273446] [0m[33mpci_bus 0000:00[0m: resource 8 [mem 0x100000000-0x17fffffff window]
[32m[    0.274248] [0m[33mNET[0m: Registered protocol family 2
[32m[    0.275027] [0m[33mtcp_listen_portaddr_hash hash table entries[0m: 512 (order: 1, 8192 bytes)
[32m[    0.277121] [0m[33mTCP established hash table entries[0m: 8192 (order: 4, 65536 bytes)
[32m[    0.278481] [0m[33mTCP bind hash table entries[0m: 8192 (order: 5, 131072 bytes)
[32m[    0.279423] [0m[33mTCP[0m: Hash tables configured (established 8192 bind 8192)
[32m[    0.280319] [0m[33mUDP hash table entries[0m: 512 (order: 2, 16384 bytes)
[32m[    0.281136] [0m[33mUDP-Lite hash table entries[0m: 512 (order: 2, 16384 bytes)
[32m[    0.281987] [0m[33mNET[0m: Registered protocol family 1
[32m[    0.282754] [0m[33mRPC[0m: Registered named UNIX socket transport module.
[32m[    0.283501] [0m[33mRPC[0m: Registered udp transport module.
[32m[    0.284202] [0m[33mRPC[0m: Registered tcp transport module.
[32m[    0.284907] [0m[33mRPC[0m: Registered tcp NFSv4.1 backchannel transport module.
[32m[    0.285773] [0m[33mpci 0000:00:01.0[0m: PIIX3: Enabling Passive Release
[32m[    0.286522] [0m[33mpci 0000:00:00.0[0m: Limiting direct PCI/PCI transfers
[32m[    0.287270] [0m[33mpci 0000:00:01.0[0m: Activating ISA DMA hang workarounds
[32m[    0.302919] [0mPCI Interrupt Link [LNKD] enabled at IRQ 11
[32m[    0.317917] [0m[33mpci 0000:00:01.2[0m: quirk_usb_early_handoff+0x0/0x61d took 29182 usecs
[32m[    0.319282] [0m[33mpci 0000:00:02.0[0m: Video device with shadowed ROM at [mem 0x000c0000-0x000dffff]
[32m[    0.320551] [0m[33mPCI[0m: CLS 0 bytes, default 64
[32m[    0.321403] [0m[33mcheck[0m: Scanning for low memory corruption every 60 seconds
[32m[    0.322466] [0mInitialise system trusted keyrings
[32m[    0.323200] [0m[33mworkingset[0m: timestamp_bits=56 max_order=18 bucket_order=0
[32m[    0.326153] [0m[33mNFS[0m: Registering the id_resolver key type
[32m[    0.326911] [0mKey type id_resolver registered
[32m[    0.327604] [0mKey type id_legacy registered
[32m[    0.328630] [0mKey type asymmetric registered
[32m[    0.329406] [0mAsymmetric key parser 'x509' registered
[32m[    0.330119] [0mBlock layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[32m[    0.331352] [0mio scheduler mq-deadline registered
[32m[    0.332059] [0mio scheduler kyber registered
[32m[    0.332842] [0m[33minput[0m: Power Button as /devices/LNXSYSTM:00/LNXPWRBN:00/input/input0
[32m[    0.334088] [0m[33mACPI[0m: Power Button [PWRF]
[32m[    0.334903] [0m[33mSerial[0m: 8250/16550 driver, 4 ports, IRQ sharing enabled
[32m[    0.361445] [0m[33m00:05[0m: ttyS0 at I/O 0x3f8 (irq = 4, base_baud = 115200) is a 16550A
[32m[    0.363019] [0mNon-volatile memory driver v1.3
[32m[    0.363741] [0mLinux agpgart interface v0.103
[32m[    0.366595] [0m[33mloop[0m: module loaded
[32m[    0.367823] [0m[33mata_piix 0000:00:01.1[0m: version 2.13
[32m[    0.368713] [0m[33mscsi host0[0m: ata_piix
[32m[    0.369832] [0m[33mscsi host1[0m: ata_piix
[32m[    0.370660] [0m[33mata1[0m: PATA max MWDMA2 cmd 0x1f0 ctl 0x3f6 bmdma 0xc060 irq 14
[32m[    0.372350] [0m[33mata2[0m: PATA max MWDMA2 cmd 0x170 ctl 0x376 bmdma 0xc068 irq 15
[32m[    0.373893] [0m[33me100[0m: Intel(R) PRO/100 Network Driver, 3.5.24-k2-NAPI
[32m[    0.374984] [0m[33me100[0m: Copyright(c) 1999-2006 Intel Corporation
[32m[    0.376064] [0m[33me1000[0m: Intel(R) PRO/1000 Network Driver - version 7.3.21-k8-NAPI
[32m[    0.376969] [0m[33me1000[0m: Copyright (c) 1999-2006 Intel Corporation.
[32m[    0.394486] [0mPCI Interrupt Link [LNKC] enabled at IRQ 10
[32m[    0.535451] [0m[33mata1.01[0m: NODEV after polling detection
[32m[    0.535957] [0m[33mata1.00[0m: ATA-7: QEMU HARDDISK, 2.5+, max UDMA/100
[32m[    0.537598] [0m[33mata1.00[0m: 104857600 sectors, multi 16: LBA48 
[32m[    0.538564] [0m[33mata2.01[0m: NODEV after polling detection
[32m[    0.538854] [0m[33mata2.00[0m: ATAPI: QEMU DVD-ROM, 2.5+, max UDMA/100
[32m[    0.540591] [0m[33mscsi 0:0:0:0[0m: Direct-Access     ATA      QEMU HARDDISK    2.5+ PQ: 0 ANSI: 5
[32m[    0.542048] [0m[33msd 0:0:0:0[0m: Attached scsi generic sg0 type 0
[32m[    0.543055] [0m[33mscsi 1:0:0:0[0m: CD-ROM            QEMU     QEMU DVD-ROM     2.5+ PQ: 0 ANSI: 5
[32m[    0.544924] [0m[33msd 0:0:0:0[0m: [sda] 104857600 512-byte logical blocks: (53.7 GB/50.0 GiB)
[32m[    0.546981] [0m[33msd 0:0:0:0[0m: [sda] Write Protect is off
[32m[    0.547849] [0m[33msd 0:0:0:0[0m: [sda] Mode Sense: 00 3a 00 00
[32m[    0.553579] [0m[33msd 0:0:0:0[0m: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[32m[    0.570699] [0m[33msr 1:0:0:0[0m: [sr0] scsi3-mmc drive: 4x/4x cd/rw xa/form2 tray
[32m[    0.571656] [0m[33mcdrom[0m: Uniform CD-ROM driver Revision: 3.20
[32m[    0.572578] [0m[33m sda[0m: sda1 < sda5 sda6 sda7 > sda2 sda3
[32m[    0.574044] [0m[33msd 0:0:0:0[0m: [sda] Attached SCSI disk
[32m[    0.575259] [0m[33msr 1:0:0:0[0m: Attached scsi CD-ROM sr0
[32m[    0.575476] [0m[33msr 1:0:0:0[0m: Attached scsi generic sg1 type 5
[32m[    0.766765] [0m[33me1000 0000:00:03.0 eth0[0m: (PCI:33MHz:32-bit) 52:54:00:12:34:56
[32m[    0.767938] [0m[33me1000 0000:00:03.0 eth0[0m: Intel(R) PRO/1000 Network Connection
[32m[    0.769457] [0m[33me1000e[0m: Intel(R) PRO/1000 Network Driver - 3.2.6-k
[32m[    0.770901] [0m[33me1000e[0m: Copyright(c) 1999 - 2015 Intel Corporation.
[32m[    0.771671] [0m[33msky2[0m: driver version 1.30
[32m[    0.772533] [0m[33mehci_hcd[0m: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[32m[    0.773745] [0m[33mehci-pci[0m: EHCI PCI platform driver
[32m[    0.774790] [0m[33mohci_hcd[0m: USB 1.1 'Open' Host Controller (OHCI) Driver
[32m[    0.775900] [0m[33mohci-pci[0m: OHCI PCI platform driver
[32m[    0.776928] [0m[33muhci_hcd[0m: USB Universal Host Controller Interface driver
[32m[    0.795279] [0m[33muhci_hcd 0000:00:01.2[0m: UHCI Host Controller
[32m[    0.796071] [0m[33muhci_hcd 0000:00:01.2[0m: new USB bus registered, assigned bus number 1
[32m[    0.797452] [0m[33muhci_hcd 0000:00:01.2[0m: irq 11, io base 0x0000c040
[32m[    0.798247] [0m[33musb usb1[0m: New USB device found, idVendor=1d6b, idProduct=0001, bcdDevice= 5.02
[32m[    0.800018] [0m[33musb usb1[0m: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[32m[    0.802446] [0m[33musb usb1[0m: Product: UHCI Host Controller
[32m[    0.803655] [0m[33musb usb1[0m: Manufacturer: Linux 5.2.0-rc4 uhci_hcd
[32m[    0.804523] [0m[33musb usb1[0m: SerialNumber: 0000:00:01.2
[32m[    0.805394] [0m[33mhub 1-0:1.0[0m: USB hub found
[32m[    0.806360] [0m[33mhub 1-0:1.0[0m: 2 ports detected
[32m[    0.807570] [0m[33musbcore[0m: registered new interface driver usblp
[32m[    0.808682] [0m[33musbcore[0m: registered new interface driver usb-storage
[32m[    0.809775] [0m[33mi8042[0m: PNP: PS/2 Controller [PNP0303:KBD,PNP0f13:MOU] at 0x60,0x64 irq 1,12
[32m[    0.812097] [0m[33mserio[0m: i8042 KBD port at 0x60,0x64 irq 1
[32m[    0.812821] [0m[33mserio[0m: i8042 AUX port at 0x60,0x64 irq 12
[32m[    0.813936] [0m[33minput[0m: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0/input/input1
[32m[    0.820613] [0m[33mrtc_cmos 00:00[0m: RTC can wake from S4
[32m[    0.822452] [0m[33mrtc_cmos 00:00[0m: registered as rtc0
[32m[    0.823258] [0m[33mrtc_cmos 00:00[0m: alarms up to one day, y3k, 114 bytes nvram, hpet irqs
[32m[    0.824997] [0m[33mdevice-mapper[0m: ioctl: 4.40.0-ioctl (2019-01-18) initialised: dm-devel@redhat.com
[32m[    0.826486] [0m[33mintel_pstate[0m: CPU model not supported
[32m[    0.827253] [0m[33mhidraw[0m: raw HID events driver (C) Jiri Kosina
[32m[    0.828145] [0m[33musbcore[0m: registered new interface driver usbhid
[32m[    0.828948] [0m[33musbhid[0m: USB HID core driver
[32m[    0.830937] [0mInitializing XFRM netlink socket
[32m[    0.831779] [0m[33mNET[0m: Registered protocol family 10
[32m[    0.833542] [0mSegment Routing with IPv6
[32m[    0.835334] [0m[33msit[0m: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[32m[    0.837174] [0m[33mNET[0m: Registered protocol family 17
[32m[    0.848892] [0mKey type dns_resolver registered
[32m[    0.850168] [0m[33mmce[0m: Using 10 MCE banks
[32m[    0.854853] [0m[33msched_clock[0m: Marking stable (802130875, 52673541)->(980253226, -125448810)
[32m[    0.856425] [0mregistered taskstats version 1
[32m[    0.857208] [0mLoading compiled-in X.509 certificates
[32m[    0.858130] [0m[33mPM[0m:   Magic number: 11:344:177
[32m[    0.858884] [0m[33macpi device:0d[0m: hash matches
[32m[    0.859687] [0m[33mprintk[0m: console [netcon0] enabled
[32m[    0.860425] [0m[33mnetconsole[0m: network logging started
[32m[    0.861175] [0m[33mcfg80211[0m: Loading compiled-in X.509 certificates for regulatory database
[32m[    0.862751] [0m[33mcfg80211[0m: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[32m[    0.863578] [0mALSA device list:
[32m[    0.864288] [0m  No soundcards found.
[32m[    0.864969] [0m[33mplatform regulatory.0[0m[1m: Direct firmware load for regulatory.db failed with error -2[0m
[32m[    0.866955] [0m[33mcfg80211[0m: failed to load regulatory.db
[32m[    1.323584] [0m[33mtsc[0m: Refined TSC clocksource calibration: 2600.012 MHz
[32m[    1.326255] [0m[33mclocksource[0m: tsc: mask: 0xffffffffffffffff max_cycles: 0x257a472b559, max_idle_ns: 440795210424 ns
[32m[    1.333426] [0m[33mclocksource[0m: Switched to clocksource tsc
[32m[    1.406533] [0m[33minput[0m: ImExPS/2 Generic Explorer Mouse as /devices/platform/i8042/serio1/input/input3
[32m[    1.411512] [0m[33mmd[0m: Waiting for all devices to be available before autodetect
[32m[    1.412642] [0m[33mmd[0m: If you don't use raid, use raid=noautodetect
[32m[    1.413566] [0m[33mmd[0m: Autodetecting RAID arrays.
[32m[    1.414333] [0m[33mmd[0m: autorun ...
[32m[    1.415057] [0m[33mmd[0m: ... autorun DONE.
[32m[    1.417234] [0m[33mEXT4-fs (sda5)[0m: INFO: recovery required on readonly filesystem
[32m[    1.418097] [0m[33mEXT4-fs (sda5)[0m: write access will be enabled during recovery
[32m[    1.457046] [0m[33mrandom[0m: fast init done
[32m[    1.467281] [0m[33mEXT4-fs (sda5)[0m: recovery complete
[32m[    1.470719] [0m[33mEXT4-fs (sda5)[0m: mounted filesystem with ordered data mode. Opts: (null)
[32m[    1.472260] [0m[33mVFS[0m: Mounted root (ext4 filesystem) readonly on device 8:5.
[32m[    1.473595] [0m[33mdevtmpfs[0m: mounted
[32m[    1.474538] [0m[33mFreeing unused kernel image memory[0m: 1320K
[32m[    1.475433] [0m[33mWrite protecting the kernel read-only data[0m: 20480k
[32m[    1.476613] [0m[33mFreeing unused kernel image memory[0m: 2008K
[32m[    1.477611] [0m[33mFreeing unused kernel image memory[0m: 980K
[32m[    1.478508] [0mRun /sbin/init as init process
[32m[    1.560850] [0m[33mstty (101) used greatest stack depth[0m: 13520 bytes left
[32m[    1.724705] [0m[33mudevd[178][0m: starting version 3.2.7
[32m[    1.735665] [0m[33mrandom[0m: udevd: uninitialized urandom read (16 bytes read)
[32m[    1.737203] [0m[33mrandom[0m: udevd: uninitialized urandom read (16 bytes read)
[32m[    1.738792] [0m[33mrandom[0m: udevd: uninitialized urandom read (16 bytes read)
[32m[    1.756069] [0m[33mudevd[179][0m: starting eudev-3.2.7
[32m[    1.808855] [0m[33me1000 0000:00:03.0 enp0s3[0m: renamed from eth0
[32m[    1.882186] [0m[33mcdrom_id (196) used greatest stack depth[0m: 13288 bytes left
[32m[    2.197590] [0mAdding 2097148k swap on /dev/sda2.  Priority:1 extents:1 across:2097148k 
[32m[    2.213333] [0m[33mEXT4-fs (sda5)[0m: re-mounted. Opts: (null)
[32m[    2.411564] [0m[33mEXT4-fs (sda5)[0m: re-mounted. Opts: (null)
[32m[    2.430314] [0m[33mEXT4-fs (sda3)[0m: mounted filesystem with ordered data mode. Opts: (null)
[32m[    2.434423] [0m[33mEXT4-fs (sda6)[0m: mounted filesystem with ordered data mode. Opts: (null)
[32m[    2.439801] [0m[33mEXT4-fs (sda7)[0m: mounted filesystem with ordered data mode. Opts: (null)
[32m[    3.185068] [0m[33me1000[0m: enp0s3 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
[32m[    3.187020] [0m[33mip (418) used greatest stack depth[0m: 12544 bytes left
[32m[    3.188079] [0m[33mIPv6[0m: ADDRCONF(NETDEV_CHANGE): enp0s3: link becomes ready
[32m[    3.209424] [0m[33mrandom[0m: crng init done
[32m[    3.210108] [0m[33mrandom[0m: 3 urandom warning(s) missed due to ratelimiting
[32m[    3.233688] [0m[33mip (470) used greatest stack depth[0m: 12232 bytes left
[32m[  252.195877] [0m[33mmain[0m[1m: loading out-of-tree module taints kernel.[0m
[32m[  252.198314] [0mHello world !
[32m[  262.858184] [0mCleaning up module.
[32m[  722.477420] [0m[33musb 1-1[0m: new full-speed USB device number 2 using uhci_hcd
[32m[  722.649806] [0m[33musb 1-1[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[  722.655328] [0m[33musb 1-1[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[  722.657936] [0m[33musb 1-1[0m: Product: QEMU USB Keyboard
[32m[  722.658873] [0m[33musb 1-1[0m: Manufacturer: QEMU
[32m[  722.659755] [0m[33musb 1-1[0m: SerialNumber: 68284-0000:00:01.2-1
[32m[  722.671608] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/0003:0627:0001.0001/input/input4
[32m[  722.726502] [0m[33mhid-generic 0003:0627:0001.0001[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-1/input0
[32m[  722.745187] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[  740.787720] [0m[33musb 1-1[0m: USB disconnect, device number 2
[32m[  779.447428] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
[32m[  796.037390] [0m[33musb 1-2[0m: new full-speed USB device number 3 using uhci_hcd
[32m[  796.210697] [0m[33musb 1-2[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[  796.216291] [0m[33musb 1-2[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[  796.221322] [0m[33musb 1-2[0m: Product: QEMU USB Keyboard
[32m[  796.223458] [0m[33musb 1-2[0m: Manufacturer: QEMU
[32m[  796.224305] [0m[33musb 1-2[0m: SerialNumber: 68284-0000:00:01.2-2
[32m[  796.234162] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-2/1-2:1.0/0003:0627:0001.0002/input/input5
[32m[  796.288173] [0m[33mhid-generic 0003:0627:0001.0002[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-2/input0
[32m[  796.295056] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[  802.787783] [0m[33musb 1-2[0m: USB disconnect, device number 3
[32m[  802.801772] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
[32m[  806.757459] [0m[33musb 1-1[0m: new full-speed USB device number 4 using uhci_hcd
[32m[  806.932097] [0m[33musb 1-1[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[  806.937589] [0m[33musb 1-1[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[  806.943007] [0m[33musb 1-1[0m: Product: QEMU USB Keyboard
[32m[  806.943855] [0m[33musb 1-1[0m: Manufacturer: QEMU
[32m[  806.944632] [0m[33musb 1-1[0m: SerialNumber: 68284-0000:00:01.2-1
[32m[  806.955283] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/0003:0627:0001.0003/input/input6
[32m[  807.010375] [0m[33mhid-generic 0003:0627:0001.0003[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-1/input0
[32m[  807.019778] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[  809.787646] [0m[33musb 1-1[0m: USB disconnect, device number 4
[32m[  809.798853] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
[32m[  857.197340] [0m[33musb 1-2[0m: new full-speed USB device number 5 using uhci_hcd
[32m[  857.367655] [0m[33musb 1-2[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[  857.371029] [0m[33musb 1-2[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[  857.374837] [0m[33musb 1-2[0m: Product: QEMU USB Keyboard
[32m[  857.376569] [0m[33musb 1-2[0m: Manufacturer: QEMU
[32m[  857.378192] [0m[33musb 1-2[0m: SerialNumber: 68284-0000:00:01.2-2
[32m[  857.389027] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-2/1-2:1.0/0003:0627:0001.0004/input/input7
[32m[  857.444449] [0m[33mhid-generic 0003:0627:0001.0004[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-2/input0
[32m[  857.453052] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[  862.531400] [0m[33musb 1-2[0m: USB disconnect, device number 5
[32m[  862.539926] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
[32m[  866.445414] [0m[33musb 1-1[0m: new full-speed USB device number 6 using uhci_hcd
[32m[  866.616701] [0m[33musb 1-1[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[  866.621811] [0m[33musb 1-1[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[  866.623844] [0m[33musb 1-1[0m: Product: QEMU USB Keyboard
[32m[  866.625163] [0m[33musb 1-1[0m: Manufacturer: QEMU
[32m[  866.626317] [0m[33musb 1-1[0m: SerialNumber: 68284-0000:00:01.2-1
[32m[  866.637265] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-1/1-1:1.0/0003:0627:0001.0005/input/input8
[32m[  866.692114] [0m[33mhid-generic 0003:0627:0001.0005[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-1/input0
[32m[  866.696493] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[  868.531668] [0m[33musb 1-1[0m: USB disconnect, device number 6
[32m[  868.539170] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
[32m[ 1112.931514] [0m[33mclocksource[0m[1m: timekeeping watchdog on CPU0: Marking clocksource 'tsc' as unstable because the skew is too large:[0m
[32m[ 1112.939126] [0m[33mclocksource[0m[1m:                       'hpet' wd_now: ec2607bb wd_last: e4df127b mask: ffffffff[0m
[32m[ 1112.941329] [0m[33mclocksource[0m[1m:                       'tsc' cs_now: 2a434289c98 cs_last: 2a3b0b91efc mask: ffffffffffffffff[0m
[32m[ 1112.962607] [0m[33mtsc[0m: Marking TSC unstable due to clocksource watchdog
[32m[ 1112.963641] [0m[1mTSC found unstable after boot, most likely due to broken BIOS. Use 'tsc=unstable'.[0m
[32m[ 1112.965057] [0m[33msched_clock[0m: Marking unstable (1112911034493, 52606414)<-(1113089089622, -125448810)
[32m[ 1112.964640] [0m[33mclocksource[0m: Switched to clocksource hpet
[32m[ 1807.467828] [0m[33mkworker/dying (3713) used greatest stack depth[0m: 11784 bytes left
[32m[ 1857.701604] [0m[33musb 1-2[0m: new full-speed USB device number 7 using uhci_hcd
[32m[ 1857.873237] [0m[33musb 1-2[0m: New USB device found, idVendor=0627, idProduct=0001, bcdDevice= 0.00
[32m[ 1857.879762] [0m[33musb 1-2[0m: New USB device strings: Mfr=1, Product=4, SerialNumber=11
[32m[ 1857.884756] [0m[33musb 1-2[0m: Product: QEMU USB Keyboard
[32m[ 1857.885643] [0m[33musb 1-2[0m: Manufacturer: QEMU
[32m[ 1857.886407] [0m[33musb 1-2[0m: SerialNumber: 68284-0000:00:01.2-2
[32m[ 1857.897136] [0m[33minput[0m: QEMU QEMU USB Keyboard as /devices/pci0000:00/0000:00:01.2/usb1/1-2/1-2:1.0/0003:0627:0001.0006/input/input9
[32m[ 1857.953731] [0m[33mhid-generic 0003:0627:0001.0006[0m: input,hidraw0: USB HID v1.11 Keyboard [QEMU QEMU USB Keyboard] on usb-0000:00:01.2-2/input0
[32m[ 1857.964207] [0m[33musbcore[0m: registered new interface driver keyboard_alarm
[32m[ 1860.532126] [0m[33musb 1-2[0m: USB disconnect, device number 7
[32m[ 1860.544583] [0m[33musbcore[0m: deregistering interface driver keyboard_alarm
^C
[1m[7m#[27m[1m[0m                                                                           [0m[27m[24m[J[1m[0m[1m[31mroot[0m[31m[39m[1m [0m[1min [0m[1m[33mlittle-penguin/04[0m[33m[39m[1m [0m[K[4 q[?25l[?2004h[32me[39m[32me[32mx[39m[1m[31me[1m[31mx[1m[31mi[0m[39m[0m[32me[0m[32mx[0m[32mi[32mt[39m[4 q[?25l[?2004l

Script done on 2019-07-06 14:42:19+02:00 [COMMAND_EXIT_CODE="130"]
